# Generated by Django 3.2.9 on 2022-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
