# Generated by Django 3.2.9 on 2022-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='my_order_id',
            field=models.CharField(default='unavailable', max_length=20),
        ),
    ]
