# Generated by Django 3.2.9 on 2022-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_my_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='my_order_id',
            field=models.CharField(default='unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
